name: Plasmic Sync + Build (pnpm fixed)

on:
  repository_dispatch:
    types: [plasmic]

permissions:
  contents: write
  pull-requests: write

jobs:
  plasmic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      # ✅ The critical line that actually fixes "pnpm: not found"
      - name: Install pnpm globally
        run: npm install -g pnpm@9

      # Optional but safe — ensure pnpm is really in PATH
      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install Plasmic CLI
        run: npm install -g @plasmicapp/cli

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Plasmic sync
        env:
          # ✅ Your actual token directly here (works fine if repo is private)
          PLASMIC_AUTH_TOKEN: "dW5GQmBBFeDbirVLYJcSvh4Du1ZsPqQlJY503qSpeYaCmBNkdHmaBrMzaaMTl1iVq3MTReojkblvcpYNW4qA"
        run: |
          npx plasmic sync --yes \
            --projects "fbLWaWRGx4VJXYLXBiVVDd:dW5GQmBBFeDbirVLYJcSvh4Du1ZsPqQlJY503qSpeYaCmBNkdHmaBrMzaaMTl1iVq3MTReojkblvcpYNW4qA"

      - name: Build the app
        run: pnpm run build

      - name: Commit and push changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Plasmic sync [skip ci]" || echo "No changes"
          git push
